---
##### Arnold and Porter #######

controller_credentials:
  # --- Ansible Galaxy ---
  - name: "Ansible Galaxy"
    credential_type: "Ansible Galaxy/Automation Hub API Token"
    inputs:
      username: "{{ ansible_galaxy_uname }}"
      password: "{{ ansible_galaxy_pass }}"

  # --- Machine Credentials ---
  - name: "ansible worker"
    organization: Default
    credential_type: "Machine"
    inputs:
      username: "{{ ansible_worker_uname }}"
      password: "{{ ansible_worker_pass }}"

  - name: "ansible worker linux"
    organization: "ArnoldPorter"
    credential_type: "Machine"
    inputs:
      username: "{{ ansible_worker_linux_uname }}"
      password: "{{ ansible_worker_linux_pass }}"

  - name: "Demo Credential"
    organization: "admin"
    credential_type: "Machine"
    inputs:
      username: "{{ demo_credential_uname }}"
      password: "{{ demo_credential_pass }}"

  - name: "Linux Admin ansible (new)"
    organization: "ArnoldPorter"
    credential_type: "Machine"
    inputs:
      username: "{{ linux_admin_ansible_uname }}"
      password: "{{ linux_admin_ansible_pass }}"

  - name: "console"
    organization: "Netsos"
    credential_type: "Machine"
    inputs:
      username: "{{ console_uname }}"
      password: "{{ console_pass }}"

  - name: "console_prompt"
    organization: "Netsos"
    credential_type: "Machine"
    inputs:
      username: "{{ console_prompt_uname }}"
      password: "{{ console_prompt_pass }}"

  - name: "setup"
    organization: "Netsos"
    credential_type: "Machine"
    inputs:
      username: "{{ setup_uname }}"
      password: "{{ setup_pass }}"

  # --- Vault Credentials ---
  - name: "ansible_worker_vault"
    organization: "ArnoldPorter"
    credential_type: "Vault"
    inputs:
      vault_password: "{{ ansible_worker_vault_pass }}"

  - name: "Linux Admin Vault"
    organization: "ArnoldPorter"
    credential_type: "Vault"
    inputs:
      vault_password: "{{ linux_admin_vault_pass }}"

  # --- Network Credentials ---
  - name: "avanlife"
    organization: "ArnoldPorter"
    credential_type: "Network"
    inputs:
      username: "{{ avanlife_uname }}"
      password: "{{ avanlife_pass }}"

  # --- Cisco Local User Password ---
  - name: "brokerdess"
    organization: "DA11438_e"
    credential_type: "Network"
    inputs:
      username: "{{ brokerdess_uname }}"
      password: "{{ brokerdess_pass }}"

  # --- Source Control Credentials ---
  - name: "us7github01"
    organization: "Netsos"
    credential_type: "Source Control"
    inputs:
      username: "{{ us7github01_uname }}"
      password: "{{ us7github01_pass }}"
