---
controller_credentials:
  # --- RHEL Organization Credentials ---
  - name: "RHEL-GIT Creds"
    organization: "RHEL"
    credential_type: "Source Control"
    inputs:
      username: "{{ rhel_git_uname }}"
      password: "{{ rhel_git_pass }}"

  - name: "RHEL-Machine Creds"
    organization: "RHEL"
    credential_type: "Machine"
    inputs:
      username: "{{ rhel_machine_uname }}"
      password: "{{ rhel_machine_pass }}"

  # --- Windows Organization Credentials ---
  - name: "Windows-GIT Creds"
    organization: "Windows"
    credential_type: "Source Control"
    inputs:
      username: "{{ windows_machine_uname }}"
      password: "{{ windows_git_pass }}"

  - name: "Windows-Machine Creds"
    organization: "Windows"
    credential_type: "Machine"
    inputs:
      username: "{{ windows_git_uname }}"
      password: "{{ windows_machine_pass }}"

controller_roles:
  # --- RHEL RBAC for Credentials ---
  - team: "RHEL-admin"
    credential: "RHEL-Machine Creds"
    role: "admin"
  - team: "RHEL-admin"
    credential: "RHEL-GIT Creds"
    role: "admin"
  - team: "RHEL-Operator"
    credential: "RHEL-Machine Creds"
    role: "use"

  # --- Windows RBAC for Credentials ---
  - team: "Windows-Admin"
    credential: "Windows-Machine Creds"
    role: "admin"
  - team: "Windows-Admin"
    credential: "Windows-GIT Creds"
    role: "admin"
  - team: "Windows-Operator"
    credential: "Windows-Machine Creds"
    role: "use"