---
controller_projects:
  # --- Demo Project ---
  - name: "Demo Project"
    organization: "Default"
    scm_type: "git"
    wait: true
    scm_update_on_launch: true
    scm_clean: true

  # --- Linux Projects ---
  - name: "linux-inventories"
    organization: "Default"
    scm_type: "git"
    wait: true
    scm_update_on_launch: true
    scm_clean: true

  - name: "linux-playbooks"
    organization: "Default"
    scm_type: "git"
    wait: true
    scm_update_on_launch: true
    scm_clean: true

  # --- Netops Projects ---
  - name: "netops-inventory"
    organization: "Default"
    scm_type: "git"
    wait: true
    scm_update_on_launch: true
    scm_clean: true

  - name: "netops-playbooks"
    organization: "Default"
    scm_type: "git"
    wait: true
    scm_update_on_launch: true
    scm_clean: true

  - name: "network-segmentation-automation"
    organization: "Default"
    scm_type: "git"
    wait: true
    scm_update_on_launch: true
    scm_clean: true