---
controller_projects:
  - name: "AAP CaC - NetOps"
    organization: "Default"
    description: "Ansible Automation Platform Configuration-as-Code repository — NetOps team"
    scm_type: git
    scm_url: "https://github.com/AkashMainali/AAP_CAC.git"
    scm_branch: "main"
    scm_clean: true
    scm_delete_on_update: false
    scm_track_submodules: false
    scm_update_on_launch: false
    allow_override: false

controller_inventories:
  - name: "NetOps Linux Inventory"
    organization: "Default"
    description: "NetOps Linux managed nodes"
    variables: {}

  - name: "NetOps Production Inventory"
    organization: "Default"
    description: "NetOps Production managed nodes"
    variables: {}

  - name: "NetOps Staging Inventory"
    organization: "Default"
    description: "IOS office switches - staging"
    variables:
      ansible_network_os: ios
      ansible_connection: network_cli
      ansible_become: true
      ansible_become_method: enable

  - name: "Proving Ground Inventory"
    organization: "Default"
    description: "Network proving ground / lab environment"
    variables: {}

  # --- Added for Testing ---
  - name: "Default"
    organization: "Default"
    description: "Default inventory for job templates"
    variables: {}

controller_inventory_sources:
  - name: "NetOps Linux Inventory Source"
    inventory: "NetOps Linux Inventory"
    description: "Syncs hosts from netops-linux-hosts.yml"
    source: scm
    source_project: "AAP CaC - NetOps"
    source_path: "playbooks/anp_inventory/netops-linux-hosts.yml"
    update_on_launch: true
    update_cache_timeout: 0
    overwrite: true
    overwrite_vars: true
    verbosity: 1

  - name: "NetOps Production Inventory Source"
    inventory: "NetOps Production Inventory"
    description: "Syncs hosts from netops-production-hosts.yml"
    source: scm
    source_project: "AAP CaC - NetOps"
    source_path: "playbooks/anp_inventory/netops-production-hosts.yml"
    update_on_launch: true
    update_cache_timeout: 0
    overwrite: true
    overwrite_vars: true
    verbosity: 1

  - name: "NetOps Staging Inventory Source"
    inventory: "NetOps Staging Inventory"
    description: "Syncs hosts from netops-staging-hosts.yml"
    source: scm
    source_project: "AAP CaC - NetOps"
    source_path: "playbooks/anp_inventory/netops-staging-hosts.yml"
    update_on_launch: true
    update_cache_timeout: 0
    overwrite: true
    overwrite_vars: true
    verbosity: 1

  - name: "Proving Ground Inventory Source"
    inventory: "Proving Ground Inventory"
    description: "Syncs hosts from provinggound-hosts.yml"
    source: scm
    source_project: "AAP CaC - NetOps"
    source_path: "playbooks/anp_inventory/provinggound-hosts.yml"
    update_on_launch: true
    update_cache_timeout: 0
    overwrite: true
    overwrite_vars: true
    verbosity: 1
