---
all:

  children:
    ios:

      children:
        switches:
          children:

            office_core_switches:
              children:

                kc_core:
                  hosts:
                    kc-core-01:

                mi_core:
                  hosts:
                    mi-core-01:

                am_core:
                  hosts:
                    am-core-01:

                bo_core:
                  hosts:
                    bo-core-01:

                br_core:
                  hosts:
                    br-core-01:
                
                ld_core:
                  hosts:
                    ld-core-01:

                sf_core:
                  hosts:
                    sf-core-01:

                ch_core:
                  hosts:
                    ch-core-01:
                
                ht_core:
                  hosts:
                    ht-core-01:
                
                ny_core:
                  hosts:
                    ny-core-01:

                sv_core:
                  hosts:
                    sv-core-01:
                
                nw_core:
                  hosts:
                    nw-core-01:

                sa_core:
                  hosts:
                    sa-core-01:
                
                sh_core:
                  hosts:
                    sh-core-01:

                se_core:
                  hosts:
                    se-core-01:
                
                dn_core:
                  hosts:
                    dn-core-01:
                
                dc_core:
                  hosts:
                    dc-core-01:

                la_core:
                  hosts:
                    la-core-01:

            office_distro_switches:
              children:

                dc_distro:

                  hosts:
                    dc-acc1e-01: #C9407R
                    dc-acc11e-01: #C9407R
                    dc-acc11e-02: #C9410R
                    dc-acc11w-01: #C9407R
                    dc-acc11w-02: #C9407R                      
                    dc-acc3e-01: #C9410R
                    dc-acc3e-02: #C9407R
                    dc-acc6e-01: #C9410R
                    dc-acc6e-02: #C9407R
                    dc-acc6w-01: #C9410R                      
                    dc-acc8e-01: #C9410R
                    dc-acc8w-01: #C9410R

                ld_distro:
                  hosts:
                    ld-acc25-01:
                    ld-acc28-01:
                    ld-acc29-01:
                    ld-acc30-01:

                sf_distro:
                  hosts:
                    sf-acc10-01:
                    sf-acc9-01:

                ch_distro:
                  hosts:
                    ch-acc41-01:
                    ch-acc42-01:

                ny_distro:
                  hosts:
                    ny-acc10-01:
                    ny-acc11-01:
                    ny-acc12-01:
                    ny-acc13-01: # old 45xx swtich soon to be decomissioned
                    ny-acc14-01:            
                    ny-acc2-01:
                    ny-acc3-01:
                    ny-acc5-01:
                    ny-acc6-01:
                    ny-acc7-01:
                    ny-acc8-01:
                    ny-acc9-01:

                sv_distro:
                  hosts:
                    sv-acc5-01:
                    sv-acc6-01:

                la_distro:
                  hosts:
                    la-acc43-01:
                    la-acc44-01:
                    la-acc45-01:

            management_switches:
              children:

                us1_mgnt:
                  hosts:
                    us1-mgnt-01:
                    us1-mgnt-02:

                as1_mgnt:
                  hosts:
                    as1-mgnt-01:
                    as1-mgnt-02:

                as2_mgnt:
                  hosts:
                    as2-mgnt-01:
                    as2-mgnt-02:

            outside_switches:
              children:

                us1_outside:
                  hosts:
                    us1-outside-01:
                    us1-outside-02:

                eu1_outside:
                  hosts:
                    eu1-outside-01:
                    eu1-outside-02:

                eu2_outside:
                  hosts:
                    eu2-outside-01:
                    eu2-outside-02:
                    
                dc_outside:
                  hosts:
                    dc-outside-01:

                ny_outside:
                  hosts:
                    ny-outside-01:

                am_outside:
                  hosts:
                    am-outside-01:

                ch_outside:
                  hosts:
                    ch-outside-01:

                dn_outside:
                  hosts:
                    dn-outside-01:

                ht_outside:
                  hosts:
                    ht-outside-01:

                la_outside:
                  hosts:
                    la-outside-01:

                ld_outside:
                  hosts:
                    ld-outside-01:

                sf_outside:
                  hosts:
                    sf-outside-01:

                sh_outside:
                  hosts:
                    sh-outside-01:

                sv_outside:
                  hosts:
                    sv-outside-01:

                sa_outside:
                  hosts:
                    sa-outside-01:

                nw_outside:
                  hosts:
                    nw-outside-01:

                se_outside:
                  hosts:
                    se-outside-01:

        routers:
          children:
            dc_routers:
              hosts:
                dc-cedge-02:

            eu1_routers:
              hosts:
                eu1-wan-01:
                eu1-wan-02:
                eu1-cube-01:
                eu1-ir-01:
                eu1-ir-02:

            eu2_routers:
              hosts:
                eu2-wan-01:
                eu2-ir-01:
                eu2-ir-02:

            us3_routers:
              hosts:
                us3-ir-01:
                us3-ir-02:

            sh_routers:
              hosts:
                sh-wan-cube-01:
                sh-wan-02:
                sh-ir-01:

            as1_routers:
              hosts:
                as1-wan-01:
                as1-wan-02:
                as1-cube-01-wan-02:
                as1-ir-01:
            
            as2_routers:
              hosts:
                as2-wan-01:
                as2-wan-03:

            us1_routers:
              hosts:
                us1-ir-01:
                us1-ir-02:

        all_ir_routers:
          hosts:
            eu1-ir-01:
            eu1-ir-02:
            eu2-ir-01:
            eu2-ir-02:
            us3-ir-01:
            us3-ir-02:
            sh-ir-01:
            as1-ir-01:
            us1-ir-01:
            us1-ir-02:

    nxos:

      children:

        nexus_switches:
          children:

            us1_cores:
              hosts:
                us1-core-01:
                us1-core-02:
            
            us1_edge:
              hosts:
                us1-edge-01:
                us1-edge-02:
            
            us3_cores:
              hosts:
                us3-core-01:
                us3-core-02:

            us3_access:
              hosts:
                us3-acc-a3-01:
                us3-acc-b3-01:

            eu1_cores:
              hosts:
                eu1-core-01:
                eu1-core-02:
                
            eu2_cores:
              hosts:
                eu2-core-01:
                eu2-core-02:

            as1_cores:
              hosts:
                as1-core-01:
                as1-core-02:

            as2_cores:
              hosts:
                as2-core-01:
                as2-core-02:

    panos:

      children:

        panorama:
        
          hosts:
            us1panorama01:

    meraki:

      children:

        meraki_servers:

          hosts:

            meraki_server:
# meraki section is kind of weird . . . take it up with cisco.

    by_location:
      children:

        eu_region:
          children:

            ld_all:
              children:
                ld_core:
                ld_distro:
                ld_routers:

            br_all:
              children:
                br_core:
                br_routers:

            am_all:
              children:
                am_core:
                am_outside:


        us_region:
          children:

            us_region_east:
              children:
                
                kc_all:
                  children:
                    kc_core:
                    kc_outside:
                
                mi_all:
                  children:
                    mi_core:
                    mi_outside:
              
                bo_all:
                  children:
                    bo_core:
                    bo_outside:

                dc_all:
                  children:
                    dc_core:
                    dc_distro:
                    dc_routers:
                    dc_outside:

                ch_all:
                  children:
                    ch_core:
                    ch_distro:
                    ch_routers:

                ht_all:
                  children:
                    ht_core:
                    ht_routers:

                ny_all:
                  children:
                    ny_core:
                    ny_distro:
                    ny_routers:

                nw_all:
                  children:
                    nw_core:
                    nw_routers:

            us_region_west:
              children:

                sf_all:
                  children:
                    sf_core:
                    sf_distro:
                    sf_routers:

                sv_all:
                  children:
                    sv_core:
                    sv_distro:
                    sv_routers:

                sa_all:
                  children:
                    sa_core:
                    sa_routers:

                dn_all:
                  children:
                    dn_core:
                    dn_routers:

                la_all:
                  children:
                    la_core:
                    la_distro:
                    la_routers:

            us1_all:
              children:
                us1_cores:
                us1_edge:
                us1_routers:
                us1_mgnt:
                us1_outside:

            us3_all:
              children:
                us3_routers:
                us3_cores:
                us3_access:

        asia_region:
          children:

            sh_all:
              children:
                sh_core:
                sh_routers:

            se_all:
              children:
                se_core:
                se_routers:

        as1_all:
          children:
            as1_routers:
            as1_cores:
            as1_mgnt:

        as2_all:
          children:
            as2_routers:
            as2_cores:
            as2_mgnt:


        eu1_all:
          children:
            eu1_routers:
            eu1_cores:
            eu1_outside:

        eu2_all:
          children:
            eu2_routers:
            eu2_cores:
            eu2_outside:
