---
- name: Configure Credentials and RBAC in AAP
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../env/aap_target.yml
    - configs/credentials.yml
    - configs/00-vault.yml

  tasks:
    - name: Create Credentials and Assign Roles
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch